//
//  OpenPlatfromAllRPC.h
//  NebulaAppBiz
//
//  Created by 张光宇 on 2019/2/27.
//  Copyright © 2019 Alipay. All rights reserved.
//

#import <Foundation/Foundation.h>
// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2017-12-02 00:03:11


@class mobileappconfigAppBaseInfo;

@interface mobileappconfigAppBaseInfo : NSObject

@property(nonatomic, strong) NSString* appId;
@property(nonatomic, strong) NSString* name;
@property(nonatomic, strong) NSString* iconUrl;
@property(nonatomic, strong) NSString* desc;
@property(nonatomic, strong) NSString* slogan;
@property(nonatomic, strong) NSString* version;
@property(nonatomic, strong) NSString* pkgUrl;
@property(nonatomic, strong) NSString* pkgUrlNew;
@property(nonatomic, assign) SInt32 pkgSize;
@property(nonatomic, strong) NSString* md5;
@property(nonatomic, strong) NSString* incrementPkgUrl;
@property(nonatomic, strong) NSString* h5AppCdnBaseUrl;
@property(nonatomic, strong) NSString* pkgType;
@property(nonatomic, strong) NSString* status;
@property(nonatomic, assign) BOOL alipayApp;
@property(nonatomic, strong) NSString* appSource;
@property(nonatomic, strong) NSString* thirdPkgName;
@property(nonatomic, strong) NSString* schemaUri;
@property(nonatomic, strong) NSString* pageUrl;
@property(nonatomic, strong) NSString* extra;
@property(nonatomic, assign) BOOL display;
@property(nonatomic, assign) BOOL recommand;
@property(nonatomic, assign) BOOL needAuthorize;
@property(nonatomic, assign) BOOL autoAuthorize;
@property(nonatomic, assign) BOOL autoStatus;
@property(nonatomic, strong) NSString* downloadScene;
@property(nonatomic, strong) NSString* appTag;
@property(nonatomic, strong) NSString* appIcon;
@property(nonatomic, assign) BOOL tinyApp;
@property(nonatomic, assign) SInt32 updateFrequency;
@property(nonatomic, assign) BOOL historyShow;
@end



// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2017-08-01 18:56:29


@class mobileappconfigAppBaseInfoReq;
@class mobileappconfigBaseInfoReq;
@class mobileappconfigPackInfoReq;

@interface mobileappconfigAppBaseInfoReq : NSObject

@property(nonatomic, assign) SInt32 reqType;
@property(nonatomic, strong) mobileappconfigBaseInfoReq* baseInfoReq;
@property(nonatomic, strong) mobileappconfigPackInfoReq* packInfoReq;
@end

// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2017-08-01 18:56:29


@class mobileappconfigAppBaseInfo;
@class mobileappconfigAppBaseInfoRes;

@interface mobileappconfigAppBaseInfoRes : NSObject

@property(nonatomic, assign) SInt32 resultCode;
@property(nonatomic, strong) NSString* resultMsg;
@property(nonatomic, strong) NSArray* appBaseInfos;
+ (Class)appBaseInfosElementClass;
@property(nonatomic, strong) NSString* packJson;
@end

// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2017-08-01 11:17:56

@class mobileappconfigAppBaseInfoReq;
@class mobileappconfigAppBaseInfoRes;

@interface mobileappconfigAppBasicServiceFacade : NSObject

-(mobileappconfigAppBaseInfoRes *) queryAppInfo:(mobileappconfigAppBaseInfoReq *)request;

@end

// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2017-08-01 18:56:30


@class mobileappconfigBaseInfoReq;

@interface mobileappconfigBaseInfoReq : NSObject

@property(nonatomic, strong) NSString* platform;
@property(nonatomic, assign) BOOL pre;
@property(nonatomic, assign) SInt32 width;
@property(nonatomic, strong) NSString* position;
@property(nonatomic, strong) NSString* country;
@property(nonatomic, strong) NSString* province;
@property(nonatomic, strong) NSString* city;
@property(nonatomic, strong) NSArray* appIds;
+ (Class)appIdsElementClass;
@end

// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2017-08-01 18:56:29


@class mobileappconfigPackInfoReq;

@interface mobileappconfigPackInfoReq : NSObject

@property(nonatomic, strong) NSString* platform;
@property(nonatomic, strong) NSString* system;
@property(nonatomic, strong) NSString* client;
@property(nonatomic, strong) NSString* sdk;
@property(nonatomic, strong) NSString* env;
@property(nonatomic, strong) NSString* channel;
@property(nonatomic, strong) NSString* bundleid;
@property(nonatomic, strong) NSString* query;
@property(nonatomic, strong) NSString* existed;
@property(nonatomic, strong) NSString* grayRules;
@property(nonatomic, strong) NSString* localAppInfo;
@property(nonatomic, strong) NSString* stableRpc;
@property(nonatomic, strong) NSString* scene;
@property(nonatomic, strong) NSString* preferLocal;
@property(nonatomic, strong) NSString* reqmode;
@end


