// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2022-07-27 17:55:07

package com.mpaas.demo.model;

import java.io.Serializable;

public class UpdateUserInfoResponse  implements Serializable {
    public String result;
    public Boolean success;
    public String errorCode;
    public String errorMsg;

}