// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2022-07-27 17:55:07

package com.mpaas.demo.model;

import java.io.Serializable;

public class UpdateUserInfoRequest  implements Serializable {
    public String phoneNumber;
    public String nickName;
    public String avatarAftsId;
    public String profilePhotoUrl;

}