// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2021-07-07 16:10:47

package com.mpaas.demo.model;

import java.io.Serializable;

public class VipInfo  implements Serializable {
    public Long expireTime;
    public Integer level;

}