// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2024-03-14 17:31:17

import {REQ_MODEL} from "./REQ_MODEL";

interface BannerJsonPostReq {
    _mPaaSCustomBody:REQ_MODEL;

}
export {BannerJsonPostReq}