// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2024-04-18 11:00:05


@class BannerJsonPostReq;

@interface BannerJsonPostReq : NSObject

@property(nonatomic, strong) NSString* password;
@property(nonatomic, strong) NSString* username;
@end

