// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2024-04-18 11:00:05

#import "BannerJsonPostReq.h"
#import "RpcDemoClient.h"


@implementation RpcDemoClient


-(NSString *) bannerJsonPost:(BannerJsonPostReq *)requestParam{
	DTRpcMethod *method = [[DTRpcMethod alloc] init];
	method.operationType = @"com.antcloud.request.post";
	method.checkLogin =  NO ;
	method.signCheck =  YES ;
	method.returnType =   @"@\"NSString\"";

	return [[DTRpcClient defaultClient] executeMethod:method params:@[ requestParam ? requestParam : [NSNull null]]];
}

-(NSString *) articleList0JsonPost{
    DTRpcMethod *method = [[DTRpcMethod alloc] init];
    method.operationType = @"com.antcloud.request.get";
    method.checkLogin =  NO ;
    method.signCheck =  YES ;
    method.returnType =   @"@\"NSString\"";

    return [[DTRpcClient defaultClient] executeMethod:method params:@[ ]];
}
/**************************************************************************/
@end
	
	
