// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2024-04-18 11:00:05

@class BannerJsonPostReq;

@interface RpcDemoClient : NSObject


-(NSString *) bannerJsonPost:(BannerJsonPostReq *)requestParam;
                         
-(NSString *) articleList0JsonPost;

@end
	
