// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2022-04-08 18:19:55

package com.mpaas.demo.request;

import java.io.Serializable;

public class ArticleList0JsonGetReq  implements Serializable {
    public String pass;
    public String name;

}