// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2022-04-08 18:28:46

package com.mpaas.demo.request;

import java.io.Serializable;

public class BannerJsonPostReq  implements Serializable {
    public String username;
    public String password;

}