// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2021-07-07 14:08:16

package com.mpaas.demo.request;

import java.io.Serializable;

public class FriendJsonGetReq implements Serializable {
    public String name;
    public String pass;

}