// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2021-07-07 16:10:47

package com.mpaas.demo.request;


import com.mpaas.demo.model.AccountInfo;

import java.io.Serializable;

public class PostlimitPostReq  implements Serializable {
    public AccountInfo _requestBody;

}