// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2022-07-27 17:55:07

package com.mpaas.demo.request;


import com.mpaas.demo.rpc.LoginRequest;

import java.io.Serializable;


public class WebapiMpaasMeetingUserinfoLoginPostReq implements Serializable {
    public LoginRequest _requestBody;

}