// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2022-07-27 17:55:07

package com.mpaas.demo.request;


import com.mpaas.demo.model.UpdateUserInfoRequest;

import java.io.Serializable;


public class WebapiMpaasMeetingUserinfoUpdateuserinfoPostReq implements Serializable {
    public UpdateUserInfoRequest _requestBody;

}