// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2024-04-18 11:00:13


@class ArticleList0JsonGetReq;

@interface ArticleList0JsonGetReq : NSObject

@property(nonatomic, strong) NSString* cid;
@end

