// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2024-04-18 11:00:13

#import "ArticleList0JsonGetReq.h"
#import "POCClient.h"


@implementation POCClient


-(NSString *) articleList0JsonGet:(ArticleList0JsonGetReq *)requestParam{
	DTRpcMethod *method = [[DTRpcMethod alloc] init];
	method.operationType = @"com.antcloud.request.rongduan";
	method.checkLogin =  NO ;
	method.signCheck =  YES ;
	method.returnType =   @"@\"NSString\"";

	return [[DTRpcClient defaultClient] executeMethod:method params:@[ requestParam ? requestParam : [NSNull null]]];
}

/**************************************************************************/
@end
	
	
