// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2022-07-27 17:55:07

package com.mpaas.demo.rpc;

import java.io.Serializable;

public class LoginRequest  implements Serializable {
    public String pushId;
    public String phoneNumber;
    public String smsCode;

}