// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2022-07-27 10:08:23

package com.mpaas.demo.rpc;

import com.alipay.mobile.framework.service.annotation.OperationType;
import com.alipay.mobile.framework.service.annotation.SignCheck;
import com.mpaas.demo.model.UpdateUserInfoResponse;
import com.mpaas.demo.request.WebapiMpaasMeetingUserinfoLoginPostReq;
import com.mpaas.demo.request.WebapiMpaasMeetingUserinfoUpdateuserinfoPostReq;


public interface MeetingClient {


    @SignCheck
    @OperationType("com.mpaas.meeting.userInfo.update")
    public UpdateUserInfoResponse webapiMpaasMeetingUserinfoUpdateuserinfoPost (WebapiMpaasMeetingUserinfoUpdateuserinfoPostReq requestParam);

    @SignCheck
    @OperationType("com.mpaas.meeting.login")
    public LoginResonse webapiMpaasMeetingUserinfoLoginPost (WebapiMpaasMeetingUserinfoLoginPostReq requestParam);

}