// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2021-07-07 13:58:00

package com.mpaas.demo.rpc;

import com.alipay.mobile.framework.service.annotation.OperationType;
import com.alipay.mobile.framework.service.annotation.SignCheck;
import com.mpaas.demo.model.UserInfo;
import com.mpaas.demo.request.ArticleList0JsonGetReq;
import com.mpaas.demo.request.BannerJsonPostReq;
import com.mpaas.demo.request.FriendJsonGetReq;
import com.mpaas.demo.request.PostlimitPostReq;

//默认在请求头里都会添加sign：XXXX签名;默认是开启验签

public interface RpcDemoClient {

    @SignCheck
    @OperationType("com.antcloud.request.get")
    public String friendJsonGet (FriendJsonGetReq requestParam);

    @SignCheck
    @OperationType("com.antcloud.request.get")
    public String articleList0JsonGet (ArticleList0JsonGetReq requestParam);

    @SignCheck
    @OperationType("com.antcloud.request.post")
    public String postPost ();

    @SignCheck
    @OperationType("com.antcloud.request.post")
    public String bannerJsonPost (BannerJsonPostReq requestParam);

    @SignCheck
    @OperationType("com.antcloud.request.postlimit")
    public UserInfo postlimitPost (PostlimitPostReq requestParam);

    @SignCheck
    @OperationType("com.antcloud.request.weights")
    public String weightsGet ();

    @SignCheck
    @OperationType("com.antcloud.request.exception")
    public String exceptionGet ();

    @SignCheck(value = "no")
    @OperationType("com.antcloud.request.endorsed")
    public String wxarticleChaptersJsonGet ();


}