// Generated by HybirdPB CodeGenerator(1.3.0). DO NOT EDIT!
// Generation date is 2024-04-18 11:00:19

#import "RoterClient.h"


@implementation RoterClient


-(NSString *) bannerJsonPost{
	DTRpcMethod *method = [[DTRpcMethod alloc] init];
	method.operationType = @"com.antcloud.request.router";
	method.checkLogin =  NO ;
	method.signCheck =  YES ;
	method.returnType =   @"@\"NSString\"";

	return [[DTRpcClient defaultClient] executeMethod:method params:@[ ]];
}

/**************************************************************************/
@end
	
	
