// Generated by HybirdPB CodeGenerator(1.1.6). DO NOT EDIT!
// Generation date is 2017-03-21 15:51:26

#import <APProtocolBuffers/ProtocolBuffers.h>


#import "UnionResourceBizType.pb.h"

@class UnionResourceParam;
@class NSString;
@class UnionResourceIdv;

@interface UnionResourceParam : APDPBGeneratedMessage

@property (readonly) BOOL hasBizType;
@property (readonly) BOOL hasUpdateVersion;
@property (readonly) BOOL hasIssueDesc;
@property (readonly) BOOL hasBusiness;
@property (readonly) BOOL hasCheckNew;

@property (nonatomic) UnionResourceBizType bizType ;
@property (nonatomic,strong) NSArray<NSString*>* uUID ;
@property (nonatomic,strong) NSString* updateVersion ;
@property (nonatomic,strong) NSString* issueDesc ;
@property (nonatomic,strong) NSString* business ;
@property (nonatomic,strong) NSArray<UnionResourceIdv*>* resourceIdv ;
@property (nonatomic) SInt32 checkNew ;
@end

	