// Generated by HybirdPB CodeGenerator(1.1.6). DO NOT EDIT!
// Generation date is 2017-03-21 15:51:26

#import <APProtocolBuffers/ProtocolBuffers.h>



@class UnionResourceLimit;

@interface UnionResourceLimit : APDPBGeneratedMessage

@property (readonly) BOOL hasWaittime;
@property (readonly) BOOL hasRandomtime;

@property (nonatomic) SInt32 waittime ;
@property (nonatomic) SInt32 randomtime ;
@end

	