// Generated by HybirdPB CodeGenerator(1.1.6). DO NOT EDIT!
// Generation date is 2017-03-21 15:51:27

@class UnionResourceResult;
@class UnionResourceRequest;

@interface UnionResourceFacade : NSObject


-(UnionResourceResult *) getUnionResource:(UnionResourceRequest *)request;
                              
@end
	