// Generated by HybirdPB CodeGenerator(1.1.6). DO NOT EDIT!
// Generation date is 2017-03-21 15:51:27

#import <APProtocolBuffers/ProtocolBuffers.h>



@class UnionExtraData;

@interface UnionExtraData : APDPBGeneratedMessage

@property (readonly) BOOL hasKey;
@property (readonly) BOOL hasValue;

@property (nonatomic,strong) NSString* key ;
@property (nonatomic,strong) NSString* value ;
@end

	