// Generated by HybirdPB CodeGenerator(1.1.6). DO NOT EDIT!
// Generation date is 2017-03-21 15:51:27

#import <APProtocolBuffers/ProtocolBuffers.h>



@class UnionResourceIdv;

@interface UnionResourceIdv : APDPBGeneratedMessage

@property (readonly) BOOL hasResId;
@property (readonly) BOOL hasResVersion;

@property (nonatomic,strong) NSString* resId ;
@property (nonatomic,strong) NSString* resVersion ;
@end

	