// Generated by HybirdPB CodeGenerator(1.1.6). DO NOT EDIT!
// Generation date is 2017-03-21 15:51:26

#import <APProtocolBuffers/ProtocolBuffers.h>

typedef NS_ENUM(SInt32, UnionAndroidVmType) {
	UnionAndroidVmTypeAll = 0,
	UnionAndroidVmTypeArt = 1,
	UnionAndroidVmTypeDalvik = 2,
	UnionAndroidVmTypeLemur = 3,
	UnionAndroidVmTypeAoc = 4,
};
	