// Generated by HybirdPB CodeGenerator(1.1.6). DO NOT EDIT!
// Generation date is 2017-03-21 15:51:26

#import <APProtocolBuffers/ProtocolBuffers.h>


#import "UnionPlatformType.pb.h"
#import "UnionAndroidVmType.pb.h"

@class UnionResourceParam;
@class NSString;
@class UnionResourceRequest;

@interface UnionResourceRequest : APDPBGeneratedMessage

@property (readonly) BOOL hasPlatform;
@property (readonly) BOOL hasProductId;
@property (readonly) BOOL hasProductVersion;
@property (readonly) BOOL hasReleaseVersion;
@property (readonly) BOOL hasUtdid;
@property (readonly) BOOL hasClientId;
@property (readonly) BOOL hasPhoneBrand;
@property (readonly) BOOL hasPhoneModel;
@property (readonly) BOOL hasVmType;
@property (readonly) BOOL hasChannel;
@property (readonly) BOOL hasApiLevel;
@property (readonly) BOOL hasOsVersion;
@property (readonly) BOOL hasNetType;
@property (readonly) BOOL hasExtraInfo;
@property (readonly) BOOL hasUid;
@property (readonly) BOOL hasManufacturer;

@property (nonatomic) UnionPlatformType platform ;
@property (nonatomic,strong) NSString* productId ;
@property (nonatomic,strong) NSString* productVersion ;
@property (nonatomic,strong) NSString* releaseVersion ;
@property (nonatomic,strong) NSString* utdid ;
@property (nonatomic,strong) NSString* clientId ;
@property (nonatomic,strong) NSString* phoneBrand ;
@property (nonatomic,strong) NSString* phoneModel ;
@property (nonatomic) UnionAndroidVmType vmType ;
@property (nonatomic,strong) NSString* channel ;
@property (nonatomic,strong) NSString* apiLevel ;
@property (nonatomic,strong) NSString* osVersion ;
@property (nonatomic,strong) NSString* netType ;
@property (nonatomic,strong) NSString* extraInfo ;
@property (nonatomic,strong) NSArray<UnionResourceParam*>* resourceParam ;
@property (nonatomic,strong) NSString* uid ;
@property (nonatomic,strong) NSArray<NSString*>* cpuInstructionList ;
@property (nonatomic,strong) NSString* manufacturer ;
@end

	