// Generated by HybirdPB CodeGenerator(1.1.6). DO NOT EDIT!
// Generation date is 2017-03-21 15:51:27

#import <APProtocolBuffers/ProtocolBuffers.h>

typedef NS_ENUM(SInt32, UnionResourceBizType) {
	UnionResourceBizTypeUnknown = 0,
	UnionResourceBizTypeHotpatch = 1,
	UnionResourceBizTypeBundle = 2,
	UnionResourceBizTypeBirdnest = 3,
	UnionResourceBizTypeNebula = 4,
	UnionResourceBizTypeIosdynamic = 5,
	UnionResourceBizTypeCmd = 6,
	UnionResourceBizTypeResource = 7,
};
	