// Generated by HybirdPB CodeGenerator(1.1.6). DO NOT EDIT!
// Generation date is 2017-03-21 15:51:26

#import <APProtocolBuffers/ProtocolBuffers.h>



@class UnionResourceResult;
@class UnionResourceInfo;
@class UnionResourceLimit;

@interface UnionResourceResult : APDPBGeneratedMessage

@property (readonly) BOOL hasSuccess;
@property (readonly) BOOL hasMessage;
@property (readonly) BOOL hasLimit;

@property (nonatomic) BOOL success ;
@property (nonatomic,strong) NSString* message ;
@property (nonatomic,strong) NSArray<UnionResourceInfo*>* info ;
@property (nonatomic,strong) UnionResourceLimit* limit ;
@end

	