// Generated by HybirdPB CodeGenerator(1.1.6). DO NOT EDIT!
// Generation date is 2017-03-21 15:51:26

#import <APProtocolBuffers/ProtocolBuffers.h>


#import "UnionDownloadType.pb.h"
#import "UnionStoreType.pb.h"

@class UnionResourceItem;
@class UnionExtraData;

@interface UnionResourceItem : APDPBGeneratedMessage

@property (readonly) BOOL hasResId;
@property (readonly) BOOL hasResVersion;
@property (readonly) BOOL hasResType;
@property (readonly) BOOL hasFileMD5;
@property (readonly) BOOL hasFileUrl;
@property (readonly) BOOL hasFileContent;
@property (readonly) BOOL hasBusiness;
@property (readonly) BOOL hasDownloadType;
@property (readonly) BOOL hasStoreType;
@property (readonly) BOOL hasResStatus;
@property (readonly) BOOL hasIssueDesc;
@property (readonly) BOOL hasLazyLoad;
@property (readonly) BOOL hasFileData;
@property (readonly) BOOL hasDiffMD5;
@property (readonly) BOOL hasDiffUrl;
@property (readonly) BOOL hasDiffContent;
@property (readonly) BOOL hasFrameworkId;
@property (readonly) BOOL hasQuickRun;
@property (readonly) BOOL hasRestartApp;
@property (readonly) BOOL hasImgName;

@property (nonatomic,strong) NSString* resId ;
@property (nonatomic,strong) NSString* resVersion ;
@property (nonatomic,strong) NSString* resType ;
@property (nonatomic,strong) NSString* fileMD5 ;
@property (nonatomic,strong) NSString* fileUrl ;
@property (nonatomic,strong) NSString* fileContent ;
@property (nonatomic,strong) NSString* business ;
@property (nonatomic) UnionDownloadType downloadType ;
@property (nonatomic) UnionStoreType storeType ;
@property (nonatomic) SInt32 resStatus ;
@property (nonatomic,strong) NSArray<UnionExtraData*>* resExtraData ;
@property (nonatomic,strong) NSString* issueDesc ;
@property (nonatomic) SInt32 lazyLoad ;
@property (nonatomic,strong) NSData* fileData ;
@property (nonatomic,strong) NSString* diffMD5 ;
@property (nonatomic,strong) NSString* diffUrl ;
@property (nonatomic,strong) NSString* diffContent ;
@property (nonatomic,strong) NSString* frameworkId ;
@property (nonatomic) SInt32 quickRun ;
@property (nonatomic) SInt32 restartApp ;
@property (nonatomic,strong) NSString* imgName ;
@end

	