#define  AUConstantThemes  @{   \
@"AU_COLOR1" : @"COLOR(#29AB91)", \
@"AU_COLOR2" : @"COLOR(#F15A4A)", \
@"AU_COLOR3" : @"COLOR(#FFB415)", \
@"AU_COLOR4" : @"COLOR(#2B91E2)", \
@"AU_COLOR5" : @"COLOR(#333333)", \
@"AU_COLOR6" : @"COLOR(#999999)", \
@"AU_COLOR7" : @"COLOR(#A4A9B0)", \
@"AU_COLOR8" : @"COLOR(#DDDDDD)", \
@"AU_COLOR9" : @"COLOR(#108EE9)", \
@"AU_COLOR10" : @"COLOR(#F4333C)", \
@"AU_COLOR11" : @"COLOR(#FF3B30)", \
@"AU_COLOR12" : @"COLOR(#F5F5F9)", \
@"AU_COLOR13" : @"COLOR(#EBEEEF)", \
@"AU_COLOR14" : @"COLOR_A(#000000, 0.65)", \
@"AU_COLOR15" : @"COLOR(#FFFFFF)", \
@"AU_COLOR16" : @"COLOR(#1B82D2)", \
@"AU_COLOR17" : @"COLOR_A(#333333, 0.05)", \
@"AU_COLOR18" : @"COLOR(#0B71BA)", \
@"AU_COLOR19" : @"COLOR(#BBBBBB)", \
@"AU_COLOR20" : @"COLOR(#777777)", \
@"AU_COLOR21" : @"COLOR(#000000)", \
@"AU_COLOR22" : @"COLOR(#CCCCCC)", \
@"AU_COLOR24" : @"COLOR_A(#108EE9, 0.60)", \
@"AU_COLOR28" : @"COLOR(#F5F5F5)", \
@"AU_COLOR29" : @"COLOR(#eeeeee)", \
@"AU_COLOR30" : @"COLOR(0xd9d9d9)", \
@"AU_TEXTSIZE1" : @"NUMBER(10)", \
@"AU_TEXTSIZE2" : @"NUMBER(12)", \
@"AU_TEXTSIZE3" : @"NUMBER(13)", \
@"AU_TEXTSIZE4" : @"NUMBER(14)", \
@"AU_TEXTSIZE5" : @"NUMBER(15)", \
@"AU_TEXTSIZE6" : @"NUMBER(16)", \
@"AU_TEXTSIZE7" : @"NUMBER(17)", \
@"AU_TEXTSIZE8" : @"NUMBER(18)", \
@"AU_TEXTSIZE8_BOLD" : @"NUMBER(18)", \
@"AU_TEXTSIZE9" : @"NUMBER(30)", \
@"AU_CORNER1" : @"NUMBER(3)", \
@"AU_CORNER2" : @"NUMBER(5)", \
@"AU_CORNER3" : @"NUMBER(6)", \
@"AU_CORNER4" : @"NUMBER(8)", \
@"AU_CORNER5" : @"NUMBER(2)", \
@"AU_SPACE1" : @"NUMBER(4)", \
@"AU_SPACE2" : @"NUMBER(5)", \
@"AU_SPACE3" : @"NUMBER(8)", \
@"AU_SPACE4" : @"NUMBER(12)", \
@"AU_SPACE5" : @"NUMBER(15)", \
@"AU_SPACE6" : @"NUMBER(16)", \
@"AU_SPACE7" : @"NUMBER(20)", \
@"AU_SPACE8" : @"NUMBER(24)", \
@"AU_SPACE9" : @"NUMBER(28)", \
@"AU_SPACE10" : @"NUMBER(32)", \
@"AU_SPACE11" : @"NUMBER(36)", \
@"AU_SPACE12" : @"NUMBER(40)", \
@"AU_SPACE13" : @"NUMBER(44)", \
@"AU_SPACE14" : @"NUMBER(45)", \
@"AU_SPACE15" : @"NUMBER(48)", \
@"AU_SPACE16" : @"NUMBER(52)", \
@"AU_SPACE17" : @"NUMBER(56)", \
@"AU_SPACE18" : @"NUMBER(60)", \
@"AU_SPACE19" : @"NUMBER(64)", \
@"AU_SPACE20" : @"NUMBER(30)", \
@"AU_DIVIDER_SPACE2" : @"NUMBER(1)", \
@"AU_ICONSIZE1" : @"ICON_SIZE(29 / 2, 29 / 2)", \
@"AU_ICONSIZE2" : @"ICON_SIZE(44 / 2, 44 / 2)", \
@"AU_ICONSIZE3" : @"ICON_SIZE(54 / 2, 54 / 2)", \
@"AU_ICONSIZE4" : @"ICON_SIZE(57 / 2, 57 / 2)", \
@"AU_ICONSIZE5" : @"ICON_SIZE(58 / 2, 58 / 2)", \
@"AU_ICONSIZE6" : @"ICON_SIZE(60 / 2, 60 / 2)", \
@"AU_ICONSIZE7" : @"ICON_SIZE(80 / 2, 80 / 2)", \
@"AU_ICONSIZE8" : @"ICON_SIZE(87 / 2, 87 / 2)", \
@"AU_ICONSIZE9" : @"ICON_SIZE(90 / 2, 90 / 2)", \
@"AU_ICONSIZE10" : @"ICON_SIZE(120 / 2, 120 / 2)", \
@"AU_ICONSIZE11" : @"ICON_SIZE(180 / 2, 180 / 2)", \
@"TITLEBAR_BACK_BUTTON_IMAGE_PATH" : @"PATH(APCommonUI.bundle/back_button_normal)", \
@"AU_COLOR_APP_GREEN" : @"AU_COLOR1", \
@"AU_COLOR_APP_RED" : @"AU_COLOR2", \
@"AU_COLOR_APP_YELLOW" : @"AU_COLOR3", \
@"AU_COLOR_APP_BLUE" : @"AU_COLOR4", \
@"AU_COLOR_SUB_CONTENT" : @"AU_COLOR6", \
@"AU_COLOR_ICON_DEF" : @"AU_COLOR6", \
@"AU_COLOR_ASS_CONTENT" : @"AU_COLOR7", \
@"AU_COLOR_LINE" : @"AU_COLOR8", \
@"AU_COLOR_BG_DISABLE" : @"AU_COLOR8", \
@"AU_COLOR_LINK" : @"AU_COLOR9", \
@"AU_COLOR_ERROR" : @"AU_COLOR10", \
@"AU_COLOR_KEY_REMIND" : @"AU_COLOR11", \
@"AU_COLOR_CLIENT_BG1" : @"AU_COLOR28", \
@"AU_COLOR_CLIENT_BG2" : @"AU_COLOR13", \
@"AU_COLOR_MASK" : @"AU_COLOR14", \
@"AU_COLOR_UNIVERSAL_BG" : @"AU_COLOR15", \
@"AU_COLOR_HOME_PAGE_TITLEBAR_BG" : @"AU_COLOR16", \
@"AU_COLOR_ITEM_PRESSED" : @"AU_COLOR17", \
@"AU_COLOR_LINK_PRESSED" : @"AU_COLOR18", \
@"AU_COLOR_LINK_DISABLE" : @"AU_COLOR24", \
@"AU_COLOR_TEXT_DISABLE" : @"AU_COLOR19", \
@"AU_COLOR_HINT" : @"AU_COLOR19", \
@"AU_COLOR_TITLE" : @"AU_COLOR21", \
@"AU_COLOR_MAIN_CONTENT" : @"AU_COLOR21", \
/* AUTitleBar图标颜色（左右navItem）*/\
@"TITLEBAR_ICON_COLOR" : @"AU_COLOR_LINK", \
/* AUTitleBar图标大小*/\
@"TITLEBAR_ICON_SIZE" : @"ICON_SIZE(18, 18)", \
/* AUTitleBar文本大小，不包含标题*/\
@"TITLEBAR_TEXTSIZE" : @"FONT(AU_TEXTSIZE6)", \
/* AUTitleBar文本色，不包含标题*/\
@"TITLEBAR_TEXTCOLOR" : @"AU_COLOR_LINK", \
/* segment 底部分割线颜色*/\
@"SEGMENT_BOTTOM_LINE_COLOR" : @"COLOR(#dcdcdc)", \
/* 列表标题字体*/\
@"LIST_TITLE_TEXT_FONT" : @"FONT(17)", \
/* 单行列表左右间距*/\
@"LIST_LEFT_RIGHT_MARGIN" : @"NUMBER(16)", \
@"LIST_DOUBLE_LINE_SUBTITLE_TEXT_FONT" : @"FONT(14)", \
@"LIST_SINGLE_LINE_RIGHT_SUBTITLE_TEXT_COLOR" : @"COLOR(#999999)", \
@"LIST_SINGLE_LINE_RIGHT_SUBTITLE_TEXT_FONT" : @"FONT(16)", \
@"LIST_SINGLE_LINE_STYLE_DEFAULT_LEFT_ICON_SIZE" : @"ICON_SIZE(30, 30)", \
@"TOAST_RADIUS" : @"NUMBER(2)", \
@"SUBSCRIPT_BUTTON_EDGE_MARGIN" : @"NUMBER(18)"\
}